### ISSUE TITLE
tws.game being undefined error

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#113]
`````` /Users/Alexander/Documents/Aquaforces/node_modules/yield-yield/index.js:327
            throw e;
            ^

TypeError: Cannot read property 'crews' of undefined
    at /Users/Alexander/Documents/Aquaforces/sockets/host.js:75:27
    at next (native)
    at start (/Users/Alexander/Documents/Aquaforces/node_modules/yield-yield/index.js:203:20)
    at runner (/Users/Alexander/Documents/Aquaforces/node_modules/yield-yield/index.js:335:5)
    at fnc (/Users/Alexander/Documents/Aquaforces/node_modules/yield-yield/index.js:348:7)
    at WebSocket.tws.on.e (/Users/Alexander/Documents/Aquaforces/sockets/index.js:45:36)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/Alexander/Documents/Aquaforces/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/Alexander/Documents/Aquaforces/node_modules/ws/lib/Receiver.js:536:18```
``````

**Comment by jshuaf** [comment]
Not a yield-yield problem.`tws.game`is undefined for some reason

**Comment by alexandernext** [comment]
this error's been with us since like the beginning of time

**Comment by jshuaf** [comment]
yield-yield just wraps... read the top of the stack

**Comment by alexandernext** [comment]
oops forget i ever said that -- still this error has been like this since forever -- don't think we ever fixed this since the beginning of july

**Comment by jshuaf** [comment]
Steps to reproduce?

**Comment by alexandernext** [comment]
I forgot -- but it was very specific
