### ISSUE TITLE
Webpack fails to compile

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#84]
During compilation:

```
ERROR in ./http/host/index.jsx
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/Users/Alexander/Documents/Aquaforces/http/host"
    at /Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:131:12)

ERROR in ./http/game/index.jsx
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/Users/Alexander/Documents/Aquaforces/http/game"
    at /Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:131:12)

ERROR in ./http/console/index.jsx
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread" specified in "base" at 0, attempted to resolve relative to "/Users/Alexander/Documents/Aquaforces/http/console"
    at /Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:177:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/Alexander/Documents/Aquaforces/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/Alexander/Documents/Aquaforces/node_modules/babel-loader/index.js:131:12)
```

**Comment by alexandernext** [comment]
Only appeared in latest commits -- works in `frontend` branch

**Comment by jshuaf** [comment]
All you need is a simple `npm install`

**Comment by alexandernext** [comment]
@jshuaf forget I ever asked -- that was a error specific to codio
